// src/share/component/Content.svelte
<!--
  - Copyright 2021-2022 Golden_Water
  - SPDX-License-Identifier: AGPL-3.0-only
  -->
<script lang="ts">
  export let disablePadding: boolean = false;
  export let disableRound: boolean = false;
</script>

<div class="content" class:disablePadding class:disableRound>
  <slot />
</div>

<style>
  .content {
    margin: var(--spacerWidthHalf);
    padding: var(--spacerWidthHalf);

    height: calc(100vh - var(--spacerWidth) * 2);
    border-radius: var(--contentBorderRadius);

    background-color: var(--up);
  }

  .disablePadding {
    padding: 0;
  }

  .disableRound {
    border-radius: 0;
  }
</style>

// src/renderer/main/component/content/Content.tsx
/*
 * Copyright 2021-2022 Golden_Water
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import React, { ReactNode } from "react";
import "./Content.less";

class Props {
  padding?: boolean;
}

export class Content extends React.Component<Props> {
  render(): ReactNode {
    const { children, padding } = this.props;
    const paddingClass = padding ? ` ContentPadding` : "";

    return <div className={`Content${paddingClass}`}>{children}</div>;
  }
}
