// src/share/component/Layout.svelte
<!--
  - Copyright 2021-2022 Golden_Water
  - SPDX-License-Identifier: AGPL-3.0-only
  -->
<script lang="ts">
</script>

<div class="root">
  <div class="sider">
    <slot name="sider" />
  </div>
  <div class="content">
    <slot name="content">Content</slot>
  </div>
</div>

<style lang="less">
  .root {
    display: flex;
  }

  .height {
    height: calc(100vh - var(--spacerWidthHalf) * 2);
  }

  .sider {
    .height();
  }

  .content {
    .height();
    flex-grow: 1;
  }
</style>

// src/renderer/main/component/layout/Layout.tsx
/*
 * Copyright 2021-2022 Golden_Water
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import React, { ReactNode } from "react";
import "./Layout.less";

class Props {
  sider?: ReactNode;
}

export class Layout extends React.Component<Props> {
  render(): ReactNode {
    const { children, sider } = this.props;

    return (
      <div className={"Layout"}>
        {sider ? <div className={"LayoutSider"}>{sider}</div> : ""}
        <div className={"LayoutContent"}>{children}</div>
      </div>
    );
  }
}
