// src/share/component/input/NumberInput.svelte
<!--
  - Copyright 2021-2022 Golden_Water
  - SPDX-License-Identifier: AGPL-3.0-only
  -->
<script lang="ts">
  import type { TNumberInput, TTextInput } from "./TInput";
  import TextInput from "./TextInput.svelte";

  export let props: TNumberInput = { type: "number" };

  let p: TTextInput = {
    type: "text",
    onChange(value: string) {
      props.onChange(parseValue(props.value, value, props.acceptFloat));
    },
    disabled: props.disabled,
    value: props.value.toString(),
  };

  function parseValue(previousValue, value, acceptFloat) {
    let result;

    if (acceptFloat) {
      result = parseFloat(value);
    } else {
      result = parseInt(value);
    }

    if (isNaN(result) || !isFinite(result)) {
      result = previousValue;
    }

    return result;
  }

  $: {
    if (props.value.toString() !== p.value) {
      props.value = parseValue(props.value, p.value, props.acceptFloat);

      if (!(props.acceptFloat && p.value.endsWith("."))) {
        p.value = props.value.toString();
      }
    }
  }
</script>

<TextInput bind:props={p} />

// frontend/src/share/component/input/NumberInput.tsx
/*
 * Copyright 2021-2023 Golden_Water
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { TNumberInput, TTextBaseInput } from "./TInput";
import { LayoutProps } from "framer-motion";
import { useCallback } from "react";
import { TextBaseInput } from "./TextBaseInput";
import { isFloat, isInt } from "../../utils/NumberUtils";

export function NumberInput(props: Omit<TNumberInput, "type"> & LayoutProps) {
  const { acceptFloat, checkValid, parser, stringifier, ...passableProps } =
    props;

  const validator = useCallback<TTextBaseInput<number>["checkValid"]>(
    (value) => {
      if (checkValid) {
        return checkValid(value);
      } else {
        if (acceptFloat) {
          return isFloat(value);
        } else {
          return isInt(value, 10);
        }
      }
    },
    [acceptFloat, checkValid]
  );

  const parse = useCallback<TTextBaseInput<number>["parser"]>(
    (value) => {
      if (parser) {
        return parser(value);
      } else {
        if (acceptFloat) {
          return Number.parseFloat(value);
        } else {
          return Number.parseInt(value, 10);
        }
      }
    },
    [acceptFloat, parser]
  );

  const stringify = useCallback<TTextBaseInput<number>["stringifier"]>(
    (value) => {
      if (stringifier) {
        return stringifier(value);
      } else {
        return value.toString(10);
      }
    },
    [stringifier]
  );

  return (
    <TextBaseInput
      {...passableProps}
      checkValid={validator}
      parser={parse}
      stringifier={stringify}
    />
  );
}
