// src/main/app.tsx
/*
 * Copyright 2021-2022 Golden_Water
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import React, { ReactNode } from "react";

class Props {}

class State {}

export class App extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props);

    this.state = {};
  }

  render(): ReactNode {
    return <div>main_window</div>;
  }
}

// src/main/App.svelte
<!--
  - Copyright 2021-2022 Golden_Water
  - SPDX-License-Identifier: AGPL-3.0-only
  -->

<script lang="ts">
  import {colorPlates} from "../share/style/ThemeUtils";
</script>

<div class="app" style="background-color: {$colorPlates.background};color: {$colorPlates.text};">
  main_window
</div>

<style lang="less">
  .app {
    height: 100vh;
    width: 100vw;
    overflow: auto;
  }
</style>
