// src/App.tsx
/*
 * Copyright 2021-2022 Golden_Water
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { useContext, useMemo } from "react";
import { appCtx } from "./share/app/AppCtx";
import { windows, TWindow } from "./window/Window";

export function App() {
  const ctx = useContext(appCtx);

  return useMemo(
    () =>
      (
        windows.find((it) => it.windowId == ctx.params.windowId) as TWindow
      ).window(),
    [ctx.params.windowId]
  );
}

// src/main/App.svelte
<!--
  - Copyright 2021-2022 Golden_Water
  - SPDX-License-Identifier: AGPL-3.0-only
  -->

<script lang="ts">
  import {colorPlates} from "../share/style/ThemeUtils";
</script>

<div class="app" style="background-color: {$colorPlates.background};color: {$colorPlates.text};">
  main_window
</div>

<style lang="less">
  .app {
    height: 100vh;
    width: 100vw;
    overflow: auto;
  }
</style>
